---

- name: Stop Neutron service
  ansible.builtin.import_tasks: prepare_neutron.yml
  tags:
    - stop-neutron

- name: Deploy OVN plugin
  ansible.builtin.import_tasks: ovn_deploy.yml
  tags:
    - deploy-ovn

- name: Clean the database and finish the migration
  ansible.builtin.import_tasks: finishing_the_migration.yml
  tags:
    - cleaning-bd

