---
- name: stoping neutron to aplication configurations
  shell: kolla-ansible -i {{ path_to_hosts }} stop -t neutron --yes-i-really-really-mean-it
  args:
    chdir: /etc/kolla

- name: cleaning the containers
  shell: docker rm neutron_metadata_agent neutron_l3_agent neutron_openvswitch_agent
  args:
    chdir: /etc/kolla

- name: setting the openvswitch container
  command: docker exec openvswitch_vswitchd {{ item }}
  loop:
    - ovs-vsctl del-br br-tun
    - ovs-vsctl set Bridge br-ex protocols=[]
    - ovs-vsctl set Bridge br-int protocols=[]

- name: cleaning the ip netns
  shell: ip -all netns delete
  args:
    chdir: /etc/kolla
